title: Geek's Notes
subtitle: Open your heart & Enjoy the life course
link: Homepage link
meta:
  description: Content of description meta tag
  keywords: !!seq
    - OpenWRT
    - Mobius 
    - ActionCam
    - Flytecam
    - SSD
    - Linux
  author: Edgar.Wu
master:
  name: Edgar.Wu
  about: Geeks Note for Embedded System
  email: edgar1470@gmail.com
rss:
  title: Geek's Notes
  desc: Geeks Note for Embedded System
  lang: zh-cn
  max: 10
copyright:
  owner: Edgar.Wu
  beginYear: 2014
  endYear: 2016
theme: default
codetheme: night

